# Exported and merged on 2025-11-04
version: "1"

projects:
- name: Goodrun
  environments:
  - name: development
    services:
      - type: web
        name: Team-17-Medical-Pantry
        runtime: node
        repo: https://github.com/esthertea/Team-17-Medical-Pantry
        branch: development
        plan: free
        region: oregon
        buildCommand: npm install && npm run build
        startCommand: npm start
        autoDeployTrigger: commit
        envVars:
          - key: NEXT_PUBLIC_GRAPHHOPPER_KEY
            sync: false
          - key: GEOCODING_KEY
            sync: false
          - key: NEXTAUTH_SECRET
            sync: false
          - key: DATABASE_URL
            fromDatabase:
              name: goodrun-db-dev
              property: connectionString
          - key: NODE_ENV
            sync: false
          - key: NPM_CONFIG_PRODUCTION
            sync: false

    databases:
      - name: goodrun-db-dev
        databaseName: goodrun
        user: goodrun_user
        plan: free
        region: oregon
        ipAllowList:
          - source: 0.0.0.0/0
            description: everywhere
        postgresMajorVersion: "17"
